# Generated by Django 4.1 on 2023-02-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_haed_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="haed_image", new_name="head_image",
        ),
    ]
