# Generated by Django 4.1 on 2023-02-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_file_upload1"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="file_upload1",),
    ]
